title: Structured Data
author: Greg Rahn
# email: your-email@domain.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
#
twitter_username: gregrahn
github_username:  gregrahn
permalink: /:year/:month/:day/:title/

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# production_url : http://structureddata.github.io
# disqus_url : http://structureddata.org

disqus:
  shortname: structureddata

google_analytics: UA-302138-5

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
